<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>CFG Penultima</string>
	<key>patterns</key>
	<array>
		<dict>
            <key>comment</key>
            <string>It's a comment pattern for // and #</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.cfgpol</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\/\/|#).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
            <string>comment.line.double-slash.polscript</string>

		</dict>
		<dict>
            <key>comment</key>
            <string>Get default .cfg like pol .cfg</string>
			<key>match</key>
			<string>.+(?=\=)</string>
			<key>name</key>
			<string>variable.parameter.cfgpol</string>
		</dict>
		<dict>
            <key>comment</key>
            <string>Colorize any integer number</string>
			<key>match</key>
			<string>\b(:?[1-9]+[0-9]*|0)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.cfgpol</string>
		</dict>
		<dict>
            <key>comment</key>
            <string>Colorize any integer hexadecimal number</string>
			<key>match</key>
			<string>0[xX][0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.cfgpol</string>
		</dict>
        <dict>
            <key>comment</key>
            <string>Colorize the document name before brakets {</string>
			<key>match</key>
			<string>^(?!\s|{|}).+</string>
			<key>name</key>
			<string>entity.name.function.cfgpol</string>
		</dict>
		<dict>
            <key>comment</key>
            <string>Colorize the first word inside brakets</string>
			<key>match</key>
			<string>(^\s*)([\w]+)([^\s]+)</string>
			<key>name</key>
			<string>variable.parameter.cfgpol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(:?true|false)\b</string>
			<key>name</key>
			<string>constant.language.cfgpol</string>
		</dict>
        <dict>
            <key>comment</key>
            <string>Colorize every word</string>
			<key>match</key>
			<string>\b[^\d\W]+\b</string>
			<key>name</key>
			<string>string.quoted.other.cfgpol</string>
		</dict>
        <dict>
            <key>comment</key>
            <string>Get packages names, like :ghaia:text</string>
			<key>match</key>
			<string>:([^:]*):.*</string>
			<key>name</key>
			<string>storage.modifier.cfgpol</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cfgpol</string>
</dict>
</plist>
