<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>PolScript</string>
    <key>patterns</key>
    <array>
        <!-- Single-line comments -->
        <dict>
            <key>name</key>
            <string>comment.line.double-slash.polscript</string>
            <key>match</key>
            <string>//.*</string>
        </dict>
        <!-- Multi-line comments -->
        <dict>
            <key>name</key>
            <string>comment.block.polscript</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
        </dict>
        <!-- Keywords -->
        <dict>
            <key>name</key>
            <string>keyword.control.polscript</string>
            <key>match</key>
            <string>\b(use|include|var|program|if|endif|return|else|elseif|while|endwhile|for|endfor|function|endfunction|endprogram)\b</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\s*\b(break|c(ase|ontinue)|d(e(clare|fault)|ie|o)|e(lse(if)?|nd(declare|for(each)?|if|switch|while|case)|xit)|for(each)?|if|return|switch|use|while)\b</string>
            <key>name</key>
            <string>keyword.control.polscript</string>
        </dict>
        <!-- Program and Endprogram Keywords -->
        <dict>
            <key>name</key>
            <string>storage.type.function.polscript</string>
            <key>match</key>
            <string>\b(program|endprogram)\b</string>
        </dict>
        <!-- Program Name -->
        <dict>
            <key>name</key>
            <string>entity.name.namespace.polscript</string>
            <key>match</key>
            <string>\bprogram\s+([a-zA-Z0-9_]+)\b</string>
        </dict>
        <!-- Strings -->
        <dict>
            <key>name</key>
            <string>string.quoted.double.polscript</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
        </dict>
        <!-- Numbers -->
        <dict>
            <key>name</key>
            <string>constant.numeric.polscript</string>
            <key>match</key>
            <string>\b\d+\b</string>
        </dict>
        <!-- Constants -->
        <dict>
            <key>name</key>
            <string>constant.language.polscript</string>
            <key>match</key>
            <string>\b[A-Z0-9_]+\b</string>
        </dict>
        <!-- Variables -->
        <dict>
            <key>name</key>
            <string>variable.other.polscript</string>
            <key>match</key>
            <string>\bvar\s+\w+\b</string>
        </dict>
        <!-- Functions -->
        <dict>
            <key>name</key>
            <string>entity.name.function.polscript</string>
            <key>match</key>
            <string>\bfunction\s+([a-zA-Z0-9_]+)\b</string>
        </dict>
        <!-- Methods -->
        <dict>
            <key>name</key>
            <string>entity.name.method.polscript</string>
            <key>match</key>
            <string>\b([a-zA-Z0-9_]+)\s*(?=\()</string>
        </dict>
        <!-- Operators -->
        <dict>
            <key>name</key>
            <string>keyword.operator.polscript</string>
            <key>match</key>
            <string>!=|==|:=|&lt;|&gt;|&lt;=|&gt;=|\+|-|\*|/|\.+|.-</string>
        </dict>
        <!-- Structs -->
        <dict>
            <key>name</key>
            <string>entity.name.struct.polscript</string>
            <key>begin</key>
            <string>var\s+\w+\s+:=\s+struct\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>"\w+"\s+:=\s+".*"</string>
                    <key>name</key>
                    <string>entity.name.struct.property.polscript</string>
                </dict>
            </array>
        </dict>
        <!-- Arrays -->
        <dict>
            <key>name</key>
            <string>entity.name.array.polscript</string>
            <key>begin</key>
            <string>var\s+\w+\s+:=\s+array\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>"\w+"\s+:=\s+".*"</string>
                    <key>name</key>
                    <string>entity.name.array.property.polscript</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.polscript</string>
    <key>fileTypes</key>
    <array>
        <string>src</string>
        <string>inc</string>
        <string>em</string>
    </array>
    <key>uuid</key>
    <string>deaa83ff-0713-4133-98a2-ce17ada5453b</string>
</dict>
</plist>
